<a href="https://colab.research.google.com/github/sahug/ds-tensorflow-colab/blob/master/Tensorflow%20-%20Beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensorflow - Beginners**

This short introduction uses **Keras** to:

- Load a prebuilt dataset.
- Build a neural network machine learning model that classifies images.
- Train this neural network.
- Evaluate the accuracy of the model.

In [38]:
import tensorflow as tf
print("TF Version: ", tf.__version__)

TF Version:  2.8.0


**Load Dataset**

Load and prepare the MNIST dataset. Convert the sample data **from integers to floating-point numbers:**

In [42]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


**Build Model**

Build a **tf.keras.Sequential** model by stacking layers.

In [45]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation="relu"),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)                                   
])

In [46]:
pred = model(x_train[:1]).numpy()
pred

array([[  67.82232 ,    8.139023,  -52.911324,   12.07279 , -144.65675 ,
         -60.28835 , -108.16102 ,  -41.340042,  -83.84029 ,  -17.13696 ]],
      dtype=float32)

The **tf.nn.softmax** function converts these logits to **probabilities** for each class:

In [47]:
tf.nn.softmax(pred).numpy()

array([[1.0000000e+00, 1.2019151e-26, 0.0000000e+00, 6.1416928e-25,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.2666481e-37]], dtype=float32)

Define a loss function for training using **losses.SparseCategoricalCrossentropy**, which takes **a vector of logits** and a **True** index and returns a scalar loss for each example.

In [48]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [50]:
loss_fn(y_train[:1], pred).numpy()

128.11067

Before you start **training, configure and compile** the model using **Keras Model.compile**. Set the **optimizer** class to **adam**, set the loss to the **loss_fn** function you defined earlier, and specify a **metric** to be evaluated for the model by setting the metrics parameter to accuracy.

In [51]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

**Train and evaluate your model**

In [52]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 2.7941 - accuracy: 0.7637
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.6126 - accuracy: 0.8419
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.4871 - accuracy: 0.8744
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4279 - accuracy: 0.8892
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3901 - accuracy: 0.9006


In [53]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.3027 - accuracy: 0.9367 - 543ms/epoch - 2ms/step


[0.30266073346138, 0.9366999864578247]

In [54]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [55]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.0000000e+00, 2.7994615e-14, 6.4213706e-13, 1.1016904e-11,
        3.8598513e-36, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        4.4656190e-35, 7.6840086e-25],
       [2.1219342e-17, 7.3594274e-06, 9.9940717e-01, 5.6410604e-04,
        5.6817162e-15, 1.6693997e-05, 1.6074243e-10, 4.6962637e-06,
        1.4478434e-08, 1.4938911e-23],
       [1.9495880e-37, 1.0000000e+00, 1.2560970e-13, 1.1148642e-18,
        2.8128529e-29, 3.0625129e-38, 7.6108092e-19, 9.8829405e-14,
        4.7939470e-19, 1.5291782e-26],
       [9.9999821e-01, 0.0000000e+00, 1.7893336e-06, 1.4121217e-18,
        1.9870287e-14, 5.6151694e-11, 1.6451494e-08, 2.3311218e-08,
        1.1222831e-17, 2.6266003e-12],
       [3.2235274e-20, 8.9683370e-27, 1.0136967e-10, 9.1401834e-38,
        9.9999988e-01, 3.1208673e-15, 7.3361863e-18, 1.2180392e-08,
        0.0000000e+00, 1.5467936e-07]], dtype=float32)>